version: '3.9'
services:
  agent:
    build:
      context: https://github.com/tidybee/tidybee-agent.git
    ports:
      - "8111:8111"
  hub:
    build:
      context: https://github.com/tidybee/tidybee-hub.git
    ports:
      - "5002:5002"
  frontend:
    build:
      context: git@github.com:tidybee/tidybee-frontend.git
      ssh:
        - default
    ports:
      - "8080:8080"
