version: '3.9'
services:
  agent:
    build:
      context: ./tidybee-agent
    ports:
      - "8082:8082"
  hub:
    build:
      context: ./tidybee-hub
    ports:
      - "5002:5002"
      - "5001:5001"
  frontend:
    build:
      context: ./tidybee-frontend
    ports:
      - "8080:8080"
