version: '3.9'
services:
  agent:
    build:
      context: ./tidybee-agent
    ports:
      - "8111:8111"
  hub:
    build:
      context: ./tidybee-hub
    ports:
      - "5002:5002"
  frontend:
    build:
      context: ./tidybee-frontend
    ports:
      - "8080:8080"
