services:
  agent:
    image: ghcr.io/tidybee/tidybee-agent:main
    ports:
      - "8111:8111"
    environment:
      - TIDY_ENV=docker
    depends_on:
      - hub-tidy-events
  hub-api-gateway:
    image: ghcr.io/tidybee/tidybee-hub-api-gateway:main
    ports:
      - "7001:80"
    depends_on:
      - hub-auth
      - hub-data-processing
      - hub-postgres
      - hub-tidy-events
  hub-auth:
    image: ghcr.io/tidybee/tidybee-hub-auth:main
    ports:
      - "7002:80"
    volumes:
      - ./database:/app/Database
  hub-data-processing:
    image: ghcr.io/tidybee/tidybee-hub-data-processing:main
    ports:
      - "7003:80"
    depends_on:
      hub-postgres:
        condition: service_healthy
    restart: on-failure
  hub-tidy-events:
    image: ghcr.io/tidybee/tidybee-hub-events:main
    ports:
      - "5057:8080"
    depends_on:
      hub-postgres:
        condition: service_healthy
    restart: on-failure
  hub-postgres:
    extends:
      file: hub-postgres.yml
      service: hub-postgres
  frontend:
    image: ghcr.io/tidybee/tidybee-frontend:main
    ports:
      - "8080:80"

volumes:
  pg_data:
