version: '3.9'
services:
  agent:
    build:
      context: https://github.com/tidybee/tidybee-agent.git
    ports:
      - "8111:8111"
  hub-api-gateway:
    build:
      context: https://github.com/tidybee/tidybee-hub.git#database-outside-the-scope
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "7001:80"
    depends_on:
      - hub-auth
      - hub-data-processing
  hub-auth:
    build:
      context: https://github.com/tidybee/tidybee-hub.git#database-outside-the-scope
      dockerfile: ./Auth/Dockerfile
    ports:
      - "7002:80"
    volumes:
      - ./database:/app/database
  hub-data-processing:
    build:
      context: https://github.com/tidybee/tidybee-hub.git#database-outside-the-scope
      dockerfile: ./DataProcessing/Dockerfile
    ports:
      - "7003:80"
  frontend:
    build:
      context: https://github.com/tidybee/tidybee-frontend.git
    ports:
      - "8080:8080"
