services:
  agent:
    build:
      context: ./tidybee-agent
    ports:
      - "8111:8111"
    environment:
      - TIDY_ENV=docker
    depends_on:
      - hub-tidy-events
    volumes:
      - ./test_folder:/app/tests/assets/test_folder
  hub-api-gateway:
    build:
      context: ./tidybee-hub
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "7001:80"
    depends_on:
      - hub-auth
      - hub-data-processing
      - hub-postgres
      - hub-tidy-events
  hub-auth:
    build:
      context: ./tidybee-hub
      dockerfile: ./Auth/Dockerfile
    ports:
      - "7002:80"
    volumes:
      - ./database:/app/Database
  hub-data-processing:
    build:
      context: ./tidybee-hub
      dockerfile: ./DataProcessing/Dockerfile
    ports:
      - "7003:80"
    depends_on:
      hub-postgres:
        condition: service_healthy
    restart: on-failure
  hub-tidy-events:
    build:
      context: ./tidybee-hub
      dockerfile: ./TidyEvents/Dockerfile
    ports:
      - "5057:8080"
    depends_on:
      hub-postgres:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./gcloud_service_account_keys.json:/app/gcloud_service_account_keys.json
  hub-postgres:
    extends:
      file: ./tidybee-scripts/compose/hub-postgres.yml
      service: hub-postgres
  frontend:
    build:
      context: ./tidybee-frontend
    ports:
      - "8080:80"
    depends_on:
    - grpc-web-proxy
  
  grpc-web-proxy:
    build:
      context: ./tidybee-scripts/compose/grpc-web-proxy  # Path to the directory containing the Dockerfile
    container_name: grpc-web-proxy
    command:
      - --backend_addr=hub-tidy-events:8080  # Point to your gRPC backend
      - --run_tls_server=false
      - --allow_all_origins
      - --server_http_debug_port=8081
    ports:
      - "8081:8081"  # Exposing the gRPC-Web proxy on port 8081
    depends_on:
      - hub-tidy-events

volumes:
  pg_data:
