version: '3.9'
services:
  agent:
    build:
      context: ./tidybee-agent
    ports:
      - "8111:8111"
    environment:
      - TIDY_ENV=docker
  hub-api-gateway:
    build:
      context: ./tidybee-hub
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "7001:80"
    depends_on:
      - hub-auth
      - hub-data-processing
      - hub-postgres
  hub-auth:
    build:
      context: ./tidybee-hub
      dockerfile: ./Auth/Dockerfile
    ports:
      - "7002:80"
    volumes:
      - ./database:/app/Database
  hub-data-processing:
    build:
      context: ./tidybee-hub
      dockerfile: ./DataProcessing/Dockerfile
    ports:
      - "7003:80"
  hub-postgres:
    extends:
      file: hub-postgres.yml
      service: hub-postgres
  frontend:
    build:
      context: ./tidybee-frontend
    ports:
      - "8080:80"

volumes:
  pg_data:
