services:
  agent:
    build:
      context: ./tidybee-agent
    ports:
      - "8111:8111"
    environment:
      - TIDY_ENV=docker
    depends_on:
      - hub-tidy-events
  hub-api-gateway:
    build:
      context: ./tidybee-hub
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "7001:80"
    depends_on:
      - hub-auth
      - hub-data-processing
      - hub-postgres
      - hub-tidy-events
  hub-auth:
    build:
      context: ./tidybee-hub
      dockerfile: ./Auth/Dockerfile
    ports:
      - "7002:80"
    volumes:
      - ./database:/app/Database
  hub-data-processing:
    build:
      context: ./tidybee-hub
      dockerfile: ./DataProcessing/Dockerfile
    ports:
      - "7003:80"
  hub-tidy-events:
    build:
      context: ./tidybee-hub
      dockerfile: ./TidyEvents/Dockerfile
    ports:
      - "5057:8080"
    depends_on:
      hub-postgres:
        condition: service_healthy
    restart: on-failure
  hub-postgres:
    extends:
      file: hub-postgres.yml
      service: hub-postgres
  frontend:
    build:
      context: ./tidybee-frontend
    ports:
      - "8080:80"

volumes:
  pg_data:
