version: '3.9'
services:
  hub-postgres:
    image: postgres:16.3-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-hub-postgres.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
