services:
  hub-postgres:
    build:
      context: ./hub-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # prerequisites: https://github.com/citusdata/pg_cron?tab=readme-ov-file#setting-up-pg_cron
      POSTGRES_INITDB_ARGS: "-c shared_preload_libraries=pg_cron -c cron.database_name=db"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-hub-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:  ["CMD-SHELL", "pg_isready -h localhost -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 10s
      retries: 10

volumes:
  pg_data:
